name: package_test

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libcap-dev libpcap-dev libsystemd-dev asciidoc
      - name: Build debian package
        run: |
          make
          dpkg-buildpackage -us -uc -tc -b




